### ISSUE TITLE
Is the forums module available for download

### ISSUE THREAD

**Issue by nickaynes** [siyamandayubi/Orchardcollaboration#9]
i cannot seem to find the forum module in the source code download that is available in the public demo at www.orchardcollaboration.com. Can I download this module from somewhere , as i would like to submit tickets from forum threads.
Great project, by the way.
Nick.

**Comment by servabahmani** [comment]
Hi @nickaynes . Thanks for your interest on Orchardcollaboration. The forum module plus new reporting module is part of the commercial version. If you are interested on its terms & conditions, contact us by sending email to info@orchardcollaboration.com.

Regards,
Serveh

**Comment by nickaynes** [comment]
Yes , its sounds interesting.
Does the reporting module offer something new than the current community
version ?
Please send me info on prices , terms and conditions .
Thanks
Nick
